# Cloud Build configuration for backend
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/talkwith-backend:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/talkwith-backend:latest'
      - '.'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/talkwith-backend:$BUILD_ID']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/talkwith-backend:latest']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'talkwith-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/talkwith-backend:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'MONGO_URI=${_MONGO_URI},DATABASE_NAME=${_DATABASE_NAME},GEMINI_API_KEY=${_GEMINI_API_KEY},ELEVENLABS_API_KEY=${_ELEVENLABS_API_KEY},FLASK_ENV=production,CORS_ORIGINS=${_CORS_ORIGINS}'

images:
  - 'gcr.io/$PROJECT_ID/talkwith-backend:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/talkwith-backend:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

